# Generated by Django 2.2.28 on 2022-08-23 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220823_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='addednewapp',
            new_name='hguvgvy',
        ),
    ]
